name: Update submodules
on:
  workflow_dispatch:
  workflow_call:
jobs: 
  oos-update:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps: 
      - name: Checkout Kernel
        uses: actions/checkout@v3
        with:
          repository: Grill-Laux/kernel_oneplus_sdm845
          ref: oos/wip-upstream
      
      - name: Update KernelSU
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"   git submodule update --init --remote --recursive -f
          git clone https://github.com/tiann/KernelSU remote && cd remote
          version_ksu=$[$(git rev-list --count HEAD)+10200]
          cd - && rm -rf remote
          echo "kernelsu_release=`curl https://api.github.com/repos/tiann/KernelSU/releases/latest | jq -r .tag_name`" >> $GITHUB_ENV
          git submodule update --init --remote --recursive -f
          git commit -asm "drivers: kernelsu: Bump version to $version_ksu (${{ env.kernelsu_release }})"
          git push
